### ISSUE TITLE
Default img for club

### ISSUE THREAD

**Issue by Bcpoole** [Bcpoole/ClubLife#4]
Some clubs don't have an image, we need a default one. Maybe use [font awesome file-o](http://fontawesome.io/icon/file-o/)?

**Comment by JonathanMerklin** [comment]
+1 for font awesome. That image is fine. I'm also okay with borie.jpg

**Comment by JonathanMerklin** [comment]
@Bcpoole are we default-imaging on the backend or is this a frontend concern (if object doesn't have "img" give it one)?

**Comment by Bcpoole** [comment]
Right now the database has a url for it. I think we should handle it on the front end, do a URL exists and is image confirmation, and if that fails use the fa img

**Comment by JonathanMerklin** [comment]
lol closing
