### ISSUE TITLE
Non-standardized "Organization Meeting Time" on mongodb

### ISSUE THREAD

**Issue by Bcpoole** [Bcpoole/ClubLife#5]
Add a data-cleaning part to scrapper to handle this (datetime format or so) so we can have a nicer FindOrganizationByDayAndTime function on the backend

**Comment by JonathanMerklin** [comment]
Been busy, forgot to check Github notifications. This still an issue? I can edit it in if you haven't moved the logic or wrote your own data cleaning script.

Obviously in a real-world situation we wouldn't want to just take the JSON we scraped and then run a cleaning script, we'd want to do it all at once, but it's probably conceptually easier to just write a "clean" script on the massive JSON file we generate.

**Comment by Bcpoole** [comment]
Ya it's still open. Take either approach (although it'd be easier to just have a separate cleaner for this XD)

**Comment by JonathanMerklin** [comment]
Alright, working on it but this is definitely a nontrivial amount of work. I just did one pass where I counted every day-string that isn't e.g. "Monday","tuesday","wed" and there are 241 special cases. I can narrow it down further from there but the script is going to be super ugly with a ton of elifs lmao. Let alone the "meeting time"...

**Comment by JonathanMerklin** [comment]
@bcpoole https://github.com/Bcpoole/ClubLife/pull/1

**Comment by JonathanMerklin** [comment]
If this format is uniform/numeric enough for us to deal with, I'll go ahead and make the changes to our DB from the output JSON
