### ISSUE TITLE
Styling issue: Club main picture

### ISSUE THREAD

**Issue by JonathanMerklin** [Bcpoole/ClubLife#53]
Going to start leaving some of these TODOs as issues as I find them so I don't end up like Hal from that one scene in Malcolm in the Middle where I basically depth-first-search on things to fix and get caught going too deep.

ABXY page is especially noticeable, but club images shouldn't take up like 75% of the screen. Just a styling issue, todo later

**Comment by zababka** [comment]
Club pictures will now resize appropriately.
